-- auto Generated on 2018-05-27 14:36:34
DROP TABLE IF EXISTS account;
CREATE TABLE account(
	id VARCHAR (50) NOT NULL  COMMENT 'id',
	username VARCHAR (50) COMMENT 'username',
	password VARCHAR (50) COMMENT 'password',
	create_id VARCHAR (50) COMMENT 'createId',
	edit_id VARCHAR (50) COMMENT 'editId',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
	edit_time TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'editTime',
	is_del INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'idDel',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'account';
