-- auto Generated on 2018-05-13 18:55:17 
-- DROP TABLE IF EXISTS user; 
CREATE TABLE user(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
