-- auto Generated on 2018-05-13 00:33:59 
-- DROP TABLE IF EXISTS user; 
CREATE TABLE user(
	id INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	user_name VARCHAR (50) NOT NULL COMMENT '用户名',
	age INT (11) NOT NULL COMMENT '年龄',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
